serviceName: calorie-tracker

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 13080
  adminConnectors:
    - type: http
      port: 13081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST


swagger:
  resourcePackage: com.pranav.resource
  title: Calorie Tracker APIs
  description: APIs for adding foods

database:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password:
  url: jdbc:mariadb://localhost:3307/calorie_tracker
  properties:
    charSet: UTF-8
    useSSL: false
    allowPublicKeyRetrieval: true
    serverTimezone: UTC